### ISSUE TITLE
today after composer update display error

### ISSUE THREAD

**Issue by KingCastle** [cristianpontes/zoho-crm-client-php#31] opened 2018-04-10 08:44 UTC
![screenshot from 2018-04-10 13-15-24](https://user-images.githubusercontent.com/19357118/38546202-441a87dc-3cc1-11e8-89a5-33764f74f01e.png)

Call to undefined method Buzz\Client\Curl::setTimeout()

vendor/cristianpontes/zoho-crm-client-php/CristianPontes/ZohoCRMClient/ZohoCRMClient.php

BuzzCurl change abstract class settimeout

call
`  $ZohoAccountsClient = new ZohoCRMClient('CustomModule2', $this->Token, 'com', 0);`

**Comment by pikulsky** [comment] 2018-04-10 08:52
duplicate of #30

**Comment by cristianpontes** [comment] 2018-06-06 09:18
Fixed

**Closed by cristianpontes** 2018-06-06 09:18 UTC
